name: nrfdfu
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:

  bluez: ^0.8.2
  dart_dfu:
    path: deps/dart_dfu
  path: ^1.9.0


dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
